### ISSUE TITLE
Wrong position of generated include guards and extern "C" blocks in the Evercrypt sources

### ISSUE THREAD

**Issue by niekbouman** [project-everest/hacl-star#337]
Thank you for adding
```cpp
#if defined(__cplusplus)
extern "C" {
#endif
```
blocks in commit 1797f62

However, the placement of the header inclusion guards and those extern "C" blocks currently seems incorrect.

For example, in Hacl_Hash.h, I see 

```cpp
 /* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include "evercrypt_targetconfig.h"
#include "libintvector.h"
#include "kremlin/internal/types.h"
#include "kremlin/lowstar_endianness.h"
#include <string.h>
#include "kremlin/internal/target.h"


#ifndef __Hacl_Hash_H
#define __Hacl_Hash_H

#include "Hacl_Kremlib.h"
#include "Hacl_Spec.h"
#if defined(__cplusplus)
extern "C" {
#endif

void Hacl_Hash_MD5_legacy_update_multi(uint32_t *s, uint8_t *blocks, uint32_t n_blocks);

//...

#if defined(__cplusplus)
extern "C" {
#endif
```

While the correct ordering should be: 
```cpp
 /* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
#ifndef __Hacl_Hash_H
#define __Hacl_Hash_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "evercrypt_targetconfig.h"
#include "libintvector.h"
#include "kremlin/internal/types.h"
#include "kremlin/lowstar_endianness.h"
#include <string.h>
#include "kremlin/internal/target.h"

#include "Hacl_Kremlib.h"
#include "Hacl_Spec.h"

void Hacl_Hash_MD5_legacy_update_multi(uint32_t *s, uint8_t *blocks, uint32_t n_blocks);
//...

#if defined(__cplusplus)
extern "C" {
#endif
```

kind regards,
Niek

**Comment by msprotz** [comment]
Thanks Niek for the report, HACL* will be refreshed automatically by the nightly job within 24h.

**Comment by msprotz** [comment]
Fixed by fstarlang/kremlin@37db01d199323d9cc4f57b4b6ed4e6ad57ef2865

**Comment by niekbouman** [comment]
Dear Jonathan/Evercrypt-devs.

Thank you for addressing this; however, it seems that the issue is still there: some #include statements still appear before the include guards (and the 'extern "C" '-macros):

For example in `dist/gcc64-only/EverCrypt_CTR.h` I see
```cpp
/* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include "evercrypt_targetconfig.h"
#include "libintvector.h"
#include "kremlin/internal/types.h"
#include "kremlin/lowstar_endianness.h"
#include <string.h>
#include "kremlin/internal/target.h"


#ifndef __EverCrypt_CTR_H
#define __EverCrypt_CTR_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "Hacl_Chacha20.h"
#include "Hacl_Kremlib.h"
#include "Vale.h"
#include "EverCrypt_AutoConfig2.h"
#include "EverCrypt_Error.h"
#include "Hacl_Spec.h"

typedef struct EverCrypt_CTR_state_s_s EverCrypt_CTR_state_s;

bool
EverCrypt_CTR_uu___is_State(Spec_Agile_Cipher_cipher_alg a, EverCrypt_CTR_state_s projectee);
//...
```

I.e., the following includes should be below instead of above the include guards / extern "C" macro 
```cpp
#include "evercrypt_targetconfig.h"
#include "libintvector.h"
#include "kremlin/internal/types.h"
#include "kremlin/lowstar_endianness.h"
#include <string.h>
#include "kremlin/internal/target.h"
```
 
Kind regards,
Niek

**Comment by msprotz** [comment]
Pushed another fix, hopefully we're all good now. Thanks for the bug report!

**Comment by niekbouman** [comment]
Dear Jonathan / Evercrypt-devs,

Thank you for updating, however, unfortunately, issues remain.
After this change, the include guards, like 
```cpp
#ifndef __EverCrypt_CTR_H
#define __EverCrypt_CTR_H
```
are still in the wrong position. They should come directly after the license header.
Als near the end of the header file(s) there is an ordering issue between the include guards and the "extern C" closing-brace ('}') block.

This is the current situation:
```cpp
/* ...
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#if defined(__cplusplus)
extern "C" {
#endif

#include "evercrypt_targetconfig.h"
#include "libintvector.h"
#include "kremlin/internal/types.h"
#include "kremlin/lowstar_endianness.h"
#include <string.h>
#include "kremlin/internal/target.h"


#ifndef __EverCrypt_CTR_H
#define __EverCrypt_CTR_H

#include "Hacl_Chacha20.h"
#include "Hacl_Kremlib.h"
#include "Vale.h"
//...
#define __EverCrypt_CTR_H_DEFINED
#endif

#if defined(__cplusplus)
}
#endif
```

The correct ordering would be:

```cpp

#ifndef __EverCrypt_CTR_H
#define __EverCrypt_CTR_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "evercrypt_targetconfig.h"
#include "libintvector.h"
#include "kremlin/internal/types.h"
#include "kremlin/lowstar_endianness.h"
#include <string.h>
#include "kremlin/internal/target.h"

#include "Hacl_Chacha20.h"
#include "Hacl_Kremlib.h"
#include "Vale.h"

//...

#define __EverCrypt_CTR_H_DEFINED

#if defined(__cplusplus)
}
#endif

#endif
```

**Comment by msprotz** [comment]
Thanks Niek, I've pushed another attempt at this, thanks for the detailed suggested fix.

**Comment by msprotz** [comment]
The nightly build should push a refresh in about half an hour.

**Comment by msprotz** [comment]
This caused regressions, so I had to back it out. Currently looking at it.

**Comment by msprotz** [comment]
I've convinced myself that my proposed patch in kremlib is good, so I'm going to go with that. Also had an Everest green.

**Comment by niekbouman** [comment]
Apologies for my delayed response.

I just tested in my C++ codebase and the 'extern "C"'-macros work like a charm!
Thanks again for upstreaming this..!
